name: Distribute Monthly Salary

on:
  workflow_dispatch: # Manual Trigger Button (Safe)

jobs:
  distribute-rewards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install firebase-admin

      - name: Run Salary Script
        env:
          # GitHub Secrets se key lega
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node scripts/give-salary.js
